### ISSUE TITLE
Not concerning code but choices in the game

### ISSUE THREAD

**Issue by louisdecharson** [jplusplus/the-accountant#12]
Hello,

What should a user do when he faces an obvious cartel situation and the gameplay only let him choose between the three offers (see screenshot below), there is no way to refuse the deal.
Thanks !
![capture](https://cloud.githubusercontent.com/assets/3234544/23668780/5a5a30e0-0362-11e7-851d-663ceb3a9da6.PNG)

**Comment by n-kb** [comment]
Hello @louisdecharson , showing that corruption is systemic (as opposed to a personal choice) is the whole point of the game! In many cases, public officials cannot fight against cartels.

To know why we reached this conclusion, you can read the links provided in the "About" section. Best wishes,
