### ISSUE TITLE
The explanations on "risks" don't match the choice code

### ISSUE THREAD

**Issue by pakal** [jplusplus/the-accountant#13]
The current implementation of takeRisks() doesn't match the explanations in about page :

> this[_consequences] = _.filter(this.risks, risk => {
>         return Math.random() * 20 <= risk.value;
> });

whereas

> After each choice, there is a (risk / 10) probability of triggering a game over of the type related to the risk. E.g if legal risk is 9, user has 9 chance out of 10 to be arrested by the police at the next step.

**Comment by pirhoo** [comment]
You're right! Thanks

**Comment by pakal** [comment]
From what I saw in sources, this "risk" only triggers if the level is beyond some threshold, too, like 4 or 5, doesn't it ?

**Comment by pirhoo** [comment]
Indeed, those threshold can be set here:
https://github.com/jplusplus/the-accountant/blob/master/src/components/game/game.json#L3499

**Comment by pakal** [comment]
Yes, is it worth explaining it to users, too ?
It's a little weird if users think that they may lose randomly even if they only have 1 point of risk.
